### ISSUE TITLE
miss dist dir in v1.2.1 

### ISSUE THREAD

**Issue by lhtin** [zypox/dom-element-path#20]
Compiling is failed when I update dom-element-path to 1.2.1 from 1.2.0. I found thre miss `dist` dir in v1.2.1. Please check and thank you for your time.

**Comment by zypox** [comment]
Hey!

The `dist` dir should be automatically created during build process. Are you running the build using `yarn build` command?

**Comment by lhtin** [comment]
I think the released package should include it, which says you should run `yarn build` before publishing it to npmjs.com. If there no `dist`, then it will fail when I use it as a node module.

**Comment by zypox** [comment]
Thanks, that was indeed the case. Published 1.3.1 version with `dist` folder included.
